### ISSUE TITLE
[Documentation] threshold explanation bad formatting and confusions

### ISSUE THREAD

**Issue by Cerlancism** [NotCompsky/bpcs#1]
When viewed on Github https://github.com/NotCompsky/bpcs/blob/master/doc/bpcs.1.md, part of the explanation is rendered as `289==144`  instead of `2*8*9==144` due to markdown formatting making it italics. This probably should have written as `2 * 8 * 9 == 144`.

![image](https://user-images.githubusercontent.com/28769707/94353843-3ba35e00-00a8-11eb-948a-cc38408f95d5.png)

Also, the "value is usually in the 50s" is then turned into `1` in the example CLI usages. From the history it seemes to state that the CLI accepts values 0\~6 inclusive, but is now no longer to be found. Also, is this means the actual accepted threshold range used internally is 50\~56?

**Comment by NotCompsky** [comment]
Thanks for the input, and apologies for the long delay (returned to University)!

> the "value is usually in the 50s" is then turned into 1 in the example CLI usages. From the history it seemes to state that the CLI accepts values 0~6 inclusive, but is now no longer to be found. Also, is this means the actual accepted threshold range used internally is 50~56?

Internally, the threshold range depends on the grid size - but for the default 9x9 grid, the range is 0 to 144.  
The CLI used to accept only input values between 0 and 9, adding 50 to them internally to make the valid range 50-59, for convenience, as other values seemed unlikely to be used. This is no longer the case.

Also, just as an additional note, this documentation was written back when an 8x8 grid was the default (and only) option, hence the `and a sensible threshold value is usually in the 50s` - because 56 is half the maximum complexity of an 8x8 grid. For a 9x9 grid (the default now), a sensible value would probably be in the 70s.

**Comment by Cerlancism** [comment]
Thanks for the clarifications and the work of project. I will try this soon as right now I am using a python bpcs module but it's erroneous and buggy.
